// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_5-gmUDf7_jfbcQdqEhpATE8iArEsLdE',
    appId: '1:230099903952:web:fa4c8d852ee77ab2ed45d5',
    messagingSenderId: '230099903952',
    projectId: 'devent-9e0a1',
    authDomain: 'devent-9e0a1.firebaseapp.com',
    databaseURL: 'https://devent-9e0a1-default-rtdb.firebaseio.com',
    storageBucket: 'devent-9e0a1.firebasestorage.app',
    measurementId: 'G-B29TZND9GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaWO7ns9ay6VCdCXB2clrSUmoAX9IB-1Q',
    appId: '1:230099903952:android:6e6f4613a726bf02ed45d5',
    messagingSenderId: '230099903952',
    projectId: 'devent-9e0a1',
    databaseURL: 'https://devent-9e0a1-default-rtdb.firebaseio.com',
    storageBucket: 'devent-9e0a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBacUdQXx5DE2jTPHfOvr0q28pnlJRjBOc',
    appId: '1:230099903952:ios:d7e72b75834ce5ebed45d5',
    messagingSenderId: '230099903952',
    projectId: 'devent-9e0a1',
    databaseURL: 'https://devent-9e0a1-default-rtdb.firebaseio.com',
    storageBucket: 'devent-9e0a1.firebasestorage.app',
    iosClientId: '230099903952-k1ghb9gk4qkl7dbutm2ua6n8q6fn7uv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.devent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBacUdQXx5DE2jTPHfOvr0q28pnlJRjBOc',
    appId: '1:230099903952:ios:d7e72b75834ce5ebed45d5',
    messagingSenderId: '230099903952',
    projectId: 'devent-9e0a1',
    databaseURL: 'https://devent-9e0a1-default-rtdb.firebaseio.com',
    storageBucket: 'devent-9e0a1.firebasestorage.app',
    iosClientId: '230099903952-k1ghb9gk4qkl7dbutm2ua6n8q6fn7uv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.devent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_5-gmUDf7_jfbcQdqEhpATE8iArEsLdE',
    appId: '1:230099903952:web:fd65f9a6edc21e73ed45d5',
    messagingSenderId: '230099903952',
    projectId: 'devent-9e0a1',
    authDomain: 'devent-9e0a1.firebaseapp.com',
    databaseURL: 'https://devent-9e0a1-default-rtdb.firebaseio.com',
    storageBucket: 'devent-9e0a1.firebasestorage.app',
    measurementId: 'G-2QGCB6J57N',
  );

}